### ISSUE TITLE
App Freezes/Nothing Loads after choosing directory

### ISSUE THREAD

**Issue by AJajodia** [Nstalgic/Artemis#2]
After I select the directory, nothing happens. It loads to 100% and nothing shows up.

**Comment by Nstalgic** [comment]
> After I select the directory, nothing happens. It loads to 100% and nothing shows up.

Can you check the 'log.log' file and see if there are any errors? 
Edit: Can you also see if the 'saved_data' file is being created?

**Comment by AJajodia** [comment]
Yeah, all of them are errors, because your int() function is trying to process the version of the game I think, which is v2, a string, so its giving a value error. Here is my log file.
[log.log](https://github.com/Nstalgic/Artemis/files/8105496/log.log)

**Comment by AJajodia** [comment]
The saved_data file was created

**Comment by Danmarge** [comment]
Having the same problem. Stops at 42%
